### ISSUE TITLE
The font size change will reduce the nyaovim's response speed

### ISSUE THREAD

**Issue by haifengkao** [Nymphium/nyaovim-dynfont#1]
I have tried the following commands in nyaovim's developer tool
```
editor = document.querySelector('nyaovim-app').editor
editor.screen.changeFontSize(20);
editor.screen.changeFontSize(12);
```
After the `changeFontSize`call , the response speed of nyaovim will be significantly reduced.
Since `nyaovim-dynfont` depends on `changeFontSize` command, so it is going to slow down nyaovim as well.

**Comment by Nymphium** [comment]
Currently the font-size change can be only done through the `changeFontSize` function.
So the issue should be discussed on NyaoVim's  issues.

**Comment by haifengkao** [comment]
do you have the same issue?

**Comment by Nymphium** [comment]
I haven't ever encountered the problem.
